TABLES_LIST = [
    "ENFORCEMENT_ACTION",
    "GEOGRAPHIC_AREA",
    "LCR_SAMPLE_RESULT",
    "LCR_SAMPLE",
    "SERVICE_AREA",
    "TREATMENT",
    "WATER_SYSTEM",
    "WATER_SYSTEM_FACILITY",
    "VIOLATION",
    "VIOLATION_ENF_ASSOC"
]

EPA_REGION_ID = [i + 1 for i in range(10)]

MAX_QUERY_DATA_LIMIT_A_TIME = 10000